name: api
description: A sample command-line application with basic argument parsing.
version: 0.0.1

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  args: ^2.6.0
  shelf: ^1.4.2
  shelf_router: ^1.1.4

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.8
